version: '3.8'

networks:
  deploy-guide:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - deploy-guide
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roomly
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - deploy-guide
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
 
volumes:
  pg_data: